<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [1]:
import numpy as np
import pandas as pd

In [2]:
import numpy as np
def generate():
    vector=np.zeros(7)
    vector[2]=2
    vector[-1]=2
    print(vector)
generate()

[0. 0. 2. 0. 0. 0. 2.]


In [3]:
x = lambda a : a + 10
print(x(15))

25


### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [4]:
import numpy as np
def generate():
    vector=np.arange(0.2,2,0.2)
    print(vector)
generate()

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [5]:
import numpy as np
def generate():
    vector=np.linspace(0,2,num=11, endpoint=True)[1:-1]
    print(vector)
generate()

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [6]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate():
    new_series = series.map(lambda x: x[0].upper() + x[1:])
    #return new_series
    print(new_series)
generate() 

0              How
1               To
2            Learn
3    Data science?
dtype: object


### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [7]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
def generate():
    matrix_sub=matrix_fab-matrix_fab.mean(axis = 1, keepdims = True)
    matrix_norm=matrix_sub/(2*matrix_sub.max())
    #return matrix_fab, matrix_sub,matrix_norm
    print(matrix_fab,"\n\n", matrix_sub,"\n\n",matrix_norm)
generate()

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]] 

 [[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


In [8]:
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
matrix_sub=matrix_fab-matrix_fab.mean(axis = 1, keepdims = True)
matrix_norm=matrix_sub/(2*matrix_sub.max())
print(matrix_fab)
print(matrix_sub)
print(matrix_norm)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [9]:
import numpy as np
def generate():
    arr=np.random.random(12)
    arr1=np.array(sorted(arr,reverse=True))
    arr2=arr1.reshape(4,3)
    print(arr,"\n\n")
    print(arr1,"\n\n")
    print(arr2)
generate()

[0.53470753 0.76795136 0.39662433 0.82295504 0.23188848 0.90059044
 0.03100715 0.88563376 0.01366739 0.26201745 0.37617459 0.30942127] 


[0.90059044 0.88563376 0.82295504 0.76795136 0.53470753 0.39662433
 0.37617459 0.30942127 0.26201745 0.23188848 0.03100715 0.01366739] 


[[0.90059044 0.88563376 0.82295504]
 [0.76795136 0.53470753 0.39662433]
 [0.37617459 0.30942127 0.26201745]
 [0.23188848 0.03100715 0.01366739]]


### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [10]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    df=pd.DataFrame(data=data, index=labels)
    print(df,"\n\n")
    print(df[df['age'].isnull()])
generate()

   age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h  NaN    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1 


   age animal priority  visits
d  NaN    dog      yes       3
h  NaN    cat      yes       1


### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [11]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(data=data, index=labels)
print(df,"\n\n")
def generate():
    df['animal']=df['animal'].replace('dog','Labrador')
    df.loc['d','age']=2.7
    mean_age=df.groupby('animal')['age'].mean()
    
    print(df,"\n\n")
    print(mean_age)
generate()

   age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h  NaN    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1 


   age    animal priority  visits
a  2.5       cat      yes       1
b  3.0       cat      yes       3
c  0.5     snake       no       2
d  2.7  Labrador      yes       3
e  5.0  Labrador       no       2
f  2.0       cat       no       3
g  4.5     snake       no       1
h  NaN       cat      yes       1
i  7.0  Labrador       no       2
j  3.0  Labrador       no       1 


animal
Labrador    4.425
cat         2.500
snake       2.500
Name: age, dtype: float64


### 8.  From the given dataframe get the positions where values of two columns match?

In [12]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    same=np.where(df.fruit1==df.fruit2)
    print(df,"\n\n")
    print(same)
generate()

   fruit1  fruit2
0  orange  orange
1   apple  banana
2  banana  banana
3   apple  orange
4  banana   apple
5   apple   apple
6   apple  orange
7   apple  banana
8  banana   apple
9   apple  orange 


(array([0, 2, 5]),)


### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [13]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate():
    multiple = np.where(series%4==0)
    print(series,"\n\n")
    print(multiple)
generate()

0    6
1    5
2    6
3    2
4    8
5    4
6    1
dtype: int64 


(array([4, 5]),)


### 10. Stack two given series vertically and horizontally ? Print out both.

In [14]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate():
    V = series1.append(series2)
    print(V,"\n\n")
    
    H=pd.concat([series1,series2], axis=1)
    print(H)
    
generate()

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object 


   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
