<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 2

### 1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.

In [11]:
import numpy as np
def generate():
    arr=np.arange(-2,10,1.5)
    print(arr,"\n\n")
    arr[(arr>2) & (arr<7)]*=-1
   
    print(arr)
    
generate()

[-2.  -0.5  1.   2.5  4.   5.5  7.   8.5] 


[-2.  -0.5  1.  -2.5 -4.  -5.5  7.   8.5]


### 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.

In [12]:
import numpy as np
def generate():
    vec=np.random.random(7)
    vec[vec.argmax()]=2
    vec[vec.argmin()]=7
    print(vec,"\n\n")
    vec=np.array(sorted(vec, reverse=True))
    print(vec)
    
    
generate()

[2.         0.6779754  0.50118359 0.35135453 0.31636772 7.
 0.46150409] 


[7.         2.         0.6779754  0.50118359 0.46150409 0.35135453
 0.31636772]


### 3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.
Hint: use arctan2().

In [13]:
import numpy as np
def generate():
    matrix = np.random.random((7,2))
    print(matrix,"\n\n")
    row,column = matrix[:,0], matrix[:,1]
    radial_coordinate = np.sqrt(row**2 + column**2)
    angular_coordinate = np.arctan2(column, row)
    print(radial_coordinate,"\n\n")
    print(angular_coordinate,"\n\n")
generate()

[[0.54741651 0.17420238]
 [0.18418174 0.36211933]
 [0.10906252 0.9684323 ]
 [0.93354012 0.64345124]
 [0.01755425 0.66487091]
 [0.10758204 0.79781164]
 [0.54531805 0.83846587]] 


[0.5744661  0.40626755 0.97455413 1.13381068 0.66510261 0.80503249
 1.00019837] 


[0.30809326 1.10027518 1.45865123 0.60348103 1.54439996 1.43675844
 0.99415685] 




### 4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.

In [14]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    end= start+(step*length)
    num_seq=np.arange(start,end,step)
    print(num_seq,"\n\n")
    print(end)
    
generate(start, length, step)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33] 


35


### 5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.<br/> 
### Then transpose it to obtain arr2.  From arr2 subtract a 1*3 array with all elements 1 to get arr4.
HINT: Use reshape and transpose function.

In [15]:
import numpy as np
def generate():
    arr=np.arange(0,9)
    arr1=arr.reshape(3,3)
    print(arr,"\n\n")
    print(arr1,"\n\n")
    arr2=arr1.transpose()
    print(arr2,"\n\n")
    arr3=np.ones((1,3),dtype=int)
    print(arr3,"\n\n")
    arr4=arr2-arr3
    print(arr4)
generate()

[0 1 2 3 4 5 6 7 8] 


[[0 1 2]
 [3 4 5]
 [6 7 8]] 


[[0 3 6]
 [1 4 7]
 [2 5 8]] 


[[1 1 1]] 


[[-1  2  5]
 [ 0  3  6]
 [ 1  4  7]]


### 6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Print it out. Hint: use pd.date_range.

In [16]:
import pandas as pd
import numpy as np
def generate():
    dti=pd.date_range(start='2016-01-01', end='2016-12-31',freq='B')
    print(dti,"\n\n")
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16)
generate()

DatetimeIndex(['2016-01-01', '2016-01-04', '2016-01-05', '2016-01-06',
               '2016-01-07', '2016-01-08', '2016-01-11', '2016-01-12',
               '2016-01-13', '2016-01-14',
               ...
               '2016-12-19', '2016-12-20', '2016-12-21', '2016-12-22',
               '2016-12-23', '2016-12-26', '2016-12-27', '2016-12-28',
               '2016-12-29', '2016-12-30'],
              dtype='datetime64[ns]', length=261, freq='B') 


2016-01-01    0.302386
2016-01-04    0.327043
2016-01-05    0.667334
2016-01-06    0.118037
2016-01-07    0.015654
                ...   
2016-12-26    0.407815
2016-12-27    0.198449
2016-12-28    0.509171
2016-12-29    0.282411
2016-12-30    0.857603
Freq: B, Length: 261, dtype: float64


###  7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Sunday.

In [17]:
import pandas as pd
def generate():
    dti=pd.date_range(start='2016-01-01', end='2016-12-31',freq='B')
    print(dti,"\n\n")
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16,"\n\n")
    print(bus_2k16.resample('M').mean(),"\n\n")
    print(bus_2k16[bus_2k16.index.weekday == 0].sum())
    return None
generate()

DatetimeIndex(['2016-01-01', '2016-01-04', '2016-01-05', '2016-01-06',
               '2016-01-07', '2016-01-08', '2016-01-11', '2016-01-12',
               '2016-01-13', '2016-01-14',
               ...
               '2016-12-19', '2016-12-20', '2016-12-21', '2016-12-22',
               '2016-12-23', '2016-12-26', '2016-12-27', '2016-12-28',
               '2016-12-29', '2016-12-30'],
              dtype='datetime64[ns]', length=261, freq='B') 


2016-01-01    0.454910
2016-01-04    0.536200
2016-01-05    0.097072
2016-01-06    0.751816
2016-01-07    0.819038
                ...   
2016-12-26    0.664097
2016-12-27    0.980035
2016-12-28    0.945081
2016-12-29    0.235161
2016-12-30    0.258297
Freq: B, Length: 261, dtype: float64 


2016-01-31    0.495173
2016-02-29    0.526648
2016-03-31    0.490507
2016-04-30    0.450561
2016-05-31    0.591266
2016-06-30    0.490638
2016-07-31    0.465181
2016-08-31    0.451174
2016-09-30    0.613741
2016-10-31    0.479780
2016-11-30    0.465768
2

### 8.Given the dataframe df, In the From_To column split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.

In [18]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    print(df,"\n\n")
    temp=df['From_To'].str.split('_',expand=True)
    print(temp,"\n\n")
    temp.columns=['From','To']
    print(temp,"\n\n")
    temp['From']=temp['From'].str.capitalize()
    temp['To']=temp['To'].str.capitalize()
    print(temp)
generate()

               Airline  FlightNumber           From_To  RecentDelays
0               KLM(!)       10045.0      LoNDon_paris      [23, 47]
1    <Air France> (12)           NaN      MAdrid_miLAN            []
2  (British Airways. )       10065.0  londON_StockhOlm  [24, 43, 87]
3       12. Air France           NaN    Budapest_PaRis          [13]
4          "Swiss Air"       10085.0   Brussels_londOn      [67, 32] 


          0          1
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn 


       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn 


       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


### 9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has. 
Hint: use idxmin method.

In [19]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))
print(df)
def generate():
    print(df.sum().idxmin())
    print(len(df) - df.duplicated(keep=False).sum())
    return None
generate()

          q         r         s         t         u         v         w  \
0  0.601286  0.864936  0.861258  0.892401  0.765567  0.659148  0.529881   
1  0.409503  0.571092  0.457026  0.841796  0.694899  0.062405  0.667870   
2  0.846386  0.434078  0.374640  0.618378  0.818071  0.589057  0.254823   
3  0.428209  0.408760  0.842186  0.339212  0.438450  0.703640  0.991469   

          x         y         z  
0  0.323829  0.880605  0.258430  
1  0.327612  0.571939  0.890840  
2  0.274481  0.202263  0.867253  
3  0.765352  0.996947  0.636836  
x
4


### 10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element .
Hint: use drop_duplicates and sub methods

In [20]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    print(df.drop_duplicates(subset='int'))
    print(df.sub(df.mean(axis=0), axis=1))
    return None
generate()

   int
0    1
1    2
3    3
4    4
5    5
8    6
9    7
         int
0  -3.272727
1  -2.272727
2  -2.272727
3  -1.272727
4  -0.272727
5   0.727273
6   0.727273
7   0.727273
8   1.727273
9   2.727273
10  2.727273
