<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 2

### 1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.

In [42]:
import numpy as np
def generate():
    arr = np.arange(-2, 10, 1.5)
    arr[(arr> 2) & (arr < 7)] *= -1
    return arr
generate()

array([-2. , -0.5,  1. , -2.5, -4. , -5.5,  7. ,  8.5])

### 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.

In [4]:
import numpy as np
def generate():
    random_vector = np.random.random(7)
    random_vector[random_vector.argmax()] = 2
    random_vector[random_vector.argmin()] = 7
    modified_vector = np.array(sorted(random_vector,reverse = True))
    return modified_vector
generate()

array([7.        , 2.        , 0.62828751, 0.61034861, 0.61032376,
       0.53598851, 0.43433041])

### 3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.
Hint: use arctan2(). To know more about polar and cartesian coordinates, here's one link:  [polar and cartesian](https://www.mathsisfun.com/polar-cartesian-coordinates.html).

In [44]:
import numpy as np
def generate():
    matrix = np.random.random((7,2))
    row,column = matrix[:,0], matrix[:,1]
    radial_coordinate = np.sqrt(row**2 + column**2)
    angular_coordinate = np.arctan2(column, row)
    print(radial_coordinate)
    print(angular_coordinate) 
    return None
generate()

[1.0458437  0.6601525  0.8194799  0.89887041 1.10774291 0.6894949
 0.81906525]
[0.89482235 0.44984808 0.59231601 0.35188332 1.02584175 0.4078043
 1.52423917]


### 4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.

In [5]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    end = start + (step*length)
    num_seq = np.arange(start, end, step)
    return num_seq

generate(start, length, step)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

### 5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.<br/> 
### Then transpose it to obtain arr2.  From arr2 subtract a 1*3 array with all elements 1 to get arr4. Return arr4.
HINT: Use reshape and transpose function.

In [6]:
import numpy as np
def generate():
    arr = np.arange(0,9)                                
    arr1 = arr.reshape(3,3) 
    arr2=arr1.transpose()
    arr3=np.ones(3,dtype=int)
    arr4=arr2-arr3
    return arr4
generate()

array([[-1,  2,  5],
       [ 0,  3,  6],
       [ 1,  4,  7]])

### 6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Hint: use pd.date_range.

In [2]:
import pandas as pd
import numpy as np
def generate():
    dti = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B') 
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16)
generate()

2016-01-01    0.197396
2016-01-04    0.882713
2016-01-05    0.936723
2016-01-06    0.099042
2016-01-07    0.222626
2016-01-08    0.852258
2016-01-11    0.816943
2016-01-12    0.914218
2016-01-13    0.434846
2016-01-14    0.029262
2016-01-15    0.603027
2016-01-18    0.770215
2016-01-19    0.252731
2016-01-20    0.996966
2016-01-21    0.589482
2016-01-22    0.079442
2016-01-25    0.696698
2016-01-26    0.253586
2016-01-27    0.498949
2016-01-28    0.723041
2016-01-29    0.024924
2016-02-01    0.841638
2016-02-02    0.594337
2016-02-03    0.640402
2016-02-04    0.016608
2016-02-05    0.693539
2016-02-08    0.882241
2016-02-09    0.194776
2016-02-10    0.978465
2016-02-11    0.373243
                ...   
2016-11-21    0.219033
2016-11-22    0.628318
2016-11-23    0.439148
2016-11-24    0.855828
2016-11-25    0.837008
2016-11-28    0.755991
2016-11-29    0.564163
2016-11-30    0.595066
2016-12-01    0.342463
2016-12-02    0.758309
2016-12-05    0.477312
2016-12-06    0.182739
2016-12-07 

###  7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Monday.

In [10]:
import pandas as pd
import numpy as np
def generate():
    dti = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B') 
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16)
    print(bus_2k16.resample('M').mean())
    print(bus_2k16[bus_2k16.index.weekday == 0].sum())
    return None
generate()

2016-01-01    0.090988
2016-01-04    0.923917
2016-01-05    0.427611
2016-01-06    0.446336
2016-01-07    0.998900
2016-01-08    0.602796
2016-01-11    0.389314
2016-01-12    0.360058
2016-01-13    0.599986
2016-01-14    0.330717
2016-01-15    0.268258
2016-01-18    0.965553
2016-01-19    0.227668
2016-01-20    0.023907
2016-01-21    0.387630
2016-01-22    0.862868
2016-01-25    0.316829
2016-01-26    0.541085
2016-01-27    0.182479
2016-01-28    0.595381
2016-01-29    0.186226
2016-02-01    0.019203
2016-02-02    0.674416
2016-02-03    0.286253
2016-02-04    0.744905
2016-02-05    0.869371
2016-02-08    0.924223
2016-02-09    0.684710
2016-02-10    0.869907
2016-02-11    0.035936
                ...   
2016-11-21    0.023464
2016-11-22    0.673554
2016-11-23    0.211655
2016-11-24    0.340862
2016-11-25    0.162169
2016-11-28    0.032198
2016-11-29    0.474480
2016-11-30    0.648598
2016-12-01    0.921493
2016-12-02    0.771196
2016-12-05    0.226596
2016-12-06    0.660501
2016-12-07 

### 8.Given the dataframe df, In the From_To column split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.

In [17]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    temp = df.From_To.str.split('_', expand=True)
    temp.columns = ['From', 'To']
    temp['From'] = temp['From'].str.capitalize()
    temp['To'] = temp['To'].str.capitalize()
    return temp
generate()

From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

### 9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has.
Hint: use idxmin method.

In [18]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))
def generate():
    print(df.sum().idxmin())
    print(len(df) - df.duplicated(keep=False).sum())
    return None
generate()

t
4


### 10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element.
Hint: use drop_duplicates and sub methods

In [15]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    print(df.drop_duplicates(subset='int'))
    print(df.sub(df.mean(axis=0), axis=1))
    return None
generate()

   int
0    1
1    2
3    3
4    4
5    5
8    6
9    7
         int
0  -3.272727
1  -2.272727
2  -2.272727
3  -1.272727
4  -0.272727
5   0.727273
6   0.727273
7   0.727273
8   1.727273
9   2.727273
10  2.727273
