In [1]:
import time

time.time()

1585914720.077364

In [2]:
print(range(10))

for i in range(10):
    print(i)

range(0, 10)
0
1
2
3
4
5
6
7
8
9


In [3]:
import numpy as np
np.isscalar(False)

True

In [4]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [7]:
my_mat =[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [8]:
mat=np.array(my_mat)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
type(mat)

numpy.ndarray

In [10]:
mat[1,2]

6

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr.shape

(5,)

In [13]:
arr.ndim

1

In [14]:
mat.shape

(4, 3)

In [15]:
mat.ndim

2

In [16]:
arr.dtype

dtype('int64')

In [17]:
mat.dtype

dtype('int64')

In [18]:
ap=np.arange(0,10,2)
ap

array([0, 2, 4, 6, 8])

In [19]:
ap=np.arange(0,10,1)
ap

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_li = [1,2,3,4,5]
my_li= my_li+[2,2,2,2,2]


In [21]:
print(ap)
print(ap+2)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11]


In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(10).astype('str')

array(['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0'], dtype='<U32')

In [24]:
np.zeros(10).astype('int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.zeros((2,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones((10,3)).astype('int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
np.linspace(0,5,9
           )

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [28]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.linspace(0,100,4).astype('int')

array([  0,  33,  66, 100])

In [30]:
np.arange(0,11)/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [31]:
np.eye(2).astype('int')

array([[1, 0],
       [0, 1]])

In [32]:
np.random.rand(5)

array([0.1334221 , 0.1221685 , 0.47521393, 0.21478841, 0.77330244])

In [33]:
np.random.rand(2,2)

array([[0.95364738, 0.32482444],
       [0.66742894, 0.2494744 ]])

In [34]:
my_rndm = np.random.randn(10000)
print(my_rndm)

[-1.12601111 -0.21368653  0.27349573 ... -0.54721482  0.84313236
 -1.22990158]


In [35]:
np.std(my_rndm)

0.9968858332118244

In [36]:
my_rndm = np.random.randn(10000)
print(np.std(my_rndm))
print(my_rndm[(my_rndm>=-1) & (my_rndm<=1)].shape)

1.0121733927961394
(6768,)


In [37]:
num16 = np.random.rand(16)
print(num16)

[0.82000433 0.55864771 0.79045121 0.88192358 0.47057964 0.49349502
 0.53093424 0.10473117 0.09136692 0.56244723 0.7131955  0.37318346
 0.47262621 0.40240046 0.16965321 0.96776429]


In [38]:
num16.reshape(8,2)

array([[0.82000433, 0.55864771],
       [0.79045121, 0.88192358],
       [0.47057964, 0.49349502],
       [0.53093424, 0.10473117],
       [0.09136692, 0.56244723],
       [0.7131955 , 0.37318346],
       [0.47262621, 0.40240046],
       [0.16965321, 0.96776429]])

In [39]:
num16.reshape(2,2,2,2)

array([[[[0.82000433, 0.55864771],
         [0.79045121, 0.88192358]],

        [[0.47057964, 0.49349502],
         [0.53093424, 0.10473117]]],


       [[[0.09136692, 0.56244723],
         [0.7131955 , 0.37318346]],

        [[0.47262621, 0.40240046],
         [0.16965321, 0.96776429]]]])

In [40]:
num16.reshape(4,2,2)

array([[[0.82000433, 0.55864771],
        [0.79045121, 0.88192358]],

       [[0.47057964, 0.49349502],
        [0.53093424, 0.10473117]],

       [[0.09136692, 0.56244723],
        [0.7131955 , 0.37318346]],

       [[0.47262621, 0.40240046],
        [0.16965321, 0.96776429]]])

In [41]:
num16.reshape(2,4,2)

array([[[0.82000433, 0.55864771],
        [0.79045121, 0.88192358],
        [0.47057964, 0.49349502],
        [0.53093424, 0.10473117]],

       [[0.09136692, 0.56244723],
        [0.7131955 , 0.37318346],
        [0.47262621, 0.40240046],
        [0.16965321, 0.96776429]]])

In [42]:
num16.reshape(2,8)

array([[0.82000433, 0.55864771, 0.79045121, 0.88192358, 0.47057964,
        0.49349502, 0.53093424, 0.10473117],
       [0.09136692, 0.56244723, 0.7131955 , 0.37318346, 0.47262621,
        0.40240046, 0.16965321, 0.96776429]])

In [43]:
num16.reshape(1,16)

array([[0.82000433, 0.55864771, 0.79045121, 0.88192358, 0.47057964,
        0.49349502, 0.53093424, 0.10473117, 0.09136692, 0.56244723,
        0.7131955 , 0.37318346, 0.47262621, 0.40240046, 0.16965321,
        0.96776429]])

In [44]:
num16.reshape(16,1)

array([[0.82000433],
       [0.55864771],
       [0.79045121],
       [0.88192358],
       [0.47057964],
       [0.49349502],
       [0.53093424],
       [0.10473117],
       [0.09136692],
       [0.56244723],
       [0.7131955 ],
       [0.37318346],
       [0.47262621],
       [0.40240046],
       [0.16965321],
       [0.96776429]])

In [45]:
my_arr = np.arange(101,111)
my_arr

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [46]:
my_arr[2]

103

In [47]:
print(my_arr[2])

103


In [48]:
my_arr[1:5]

array([102, 103, 104, 105])

In [49]:
my_arr[1:5:3]

array([102, 105])

In [50]:
my_arr[1::3]

array([102, 105, 108])

In [51]:
print(id(my_arr))

140383245370272


In [52]:
my_arr[0:2]=-10
print(my_arr)

[-10 -10 103 104 105 106 107 108 109 110]


In [53]:
arr_2d=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
arr_2d
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
arr_2d[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [55]:
arr_2d[::2,::2]

array([[0, 2],
       [6, 8]])

In [56]:
arr_2d[0,0]

0

In [57]:
my_var=arr_2d[1::,:2:]
print(my_var)
print(id(my_var))

[[ 3  4]
 [ 6  7]
 [ 9 10]]
140383245378384


In [60]:
arr_ = [1,2,3,4,5]
print(arr_)
#print([arr_]>2)

[1, 2, 3, 4, 5]


In [61]:
import numpy as np

In [62]:
arr_cond=np.arange(2,7)

In [63]:
arr_cond

array([2, 3, 4, 5, 6])

In [64]:
arr_cond[[True,False,True,False,True]]

array([2, 4, 6])

In [65]:
arr_cond[[True,True,True,False,False]]

array([2, 3, 4])

In [66]:
arr_cond>4

array([False, False, False,  True,  True])

In [67]:
arr_cond[[1,3]]

array([3, 5])

In [68]:
arr_cond[[False,True,False,True,False]]

array([3, 5])

In [69]:
arr_cond=np.arange(2,16)
arr_cond

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
arr_cond>8

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True])

In [71]:
arr_cond[arr_cond>8]

array([ 9, 10, 11, 12, 13, 14, 15])

In [72]:
arr_cond[[False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True]]

array([ 9, 10, 11, 12, 13, 14, 15])

In [73]:
len(arr_cond)

14

In [74]:
arr_cond[arr_cond%2==1]

array([ 3,  5,  7,  9, 11, 13, 15])

In [75]:
arr_cond[arr_cond%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [76]:
5
6

6

In [77]:
print(5)
print(6)

5
6


In [78]:
import numpy as np

In [79]:
arr_2d=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [80]:
arr_2d.shape

(4, 3)

In [81]:
scalar=3

In [82]:
scalar

3

In [83]:
arr_2d+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [84]:
arr_2d+scalar

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [85]:
Arr_id=np.array([10,10,10])

In [86]:
Arr_id.shape

(3,)

In [87]:
print(Arr_id)
print()
print()
print(arr_2d)

[10 10 10]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [88]:
print(Arr_id+arr_2d)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [89]:
print(arr_2d+Arr_id)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [90]:
Arr_id2=np.array([[10],[10],[10]])
print(Arr_id2)

[[10]
 [10]
 [10]]


In [91]:
print(Arr_id2+arr_2d)

ValueError: operands could not be broadcast together with shapes (3,1) (4,3) 

In [92]:
print(arr_2d+Arr_id2)

ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

In [93]:
print(Arr_id+Arr_id2)

[[20 20 20]
 [20 20 20]
 [20 20 20]]


In [94]:
Arr_id4=np.array([10,10,10,10])
print(Arr_id4)

[10 10 10 10]


In [95]:
print(Arr_id2+Arr_id4)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


In [96]:
print(Arr_id2+Arr_id4)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


In [97]:
print(Arr_id4+Arr_id2)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


In [98]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr[0]=2

In [100]:
arr

array([ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr.min()

2

In [102]:
arr.max()

10

In [103]:
arr.sum()

56

In [104]:
min(arr)

2

In [105]:
max(arr)

10

In [106]:
np.min(arr)

2

In [107]:
np.max(arr)

10

In [108]:
arr

array([ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr.argmin()

0

In [110]:
arr.argmax()

9

In [111]:
arr=np.random.rand(12)
arr

array([0.33298837, 0.28598839, 0.14181804, 0.49031255, 0.32039074,
       0.47845566, 0.06854884, 0.86750595, 0.69643718, 0.77284322,
       0.78592662, 0.34507619])

In [112]:
arr.argmin()

6

In [113]:
arr.argmax()

7

In [114]:
np.sqrt(arr)

array([0.57705145, 0.53477882, 0.37658736, 0.70022322, 0.56603069,
       0.69170489, 0.26181833, 0.9314    , 0.83452812, 0.87911502,
       0.88652503, 0.58743186])

In [115]:
arr.mean()

0.46552431218865936

In [116]:
np.mean(arr)

0.46552431218865936

In [117]:
np.exp(arr)

array([1.39513108, 1.331077  , 1.15236694, 1.63282648, 1.37766596,
       1.61358056, 1.07095293, 2.3809652 , 2.00659083, 2.16591568,
       2.19443942, 1.41209751])

In [118]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [119]:
arr2d=arr.reshape(4,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [121]:
arr2d.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [122]:
var = arr2d.flatten()
var.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [123]:
arr_x=np.array([[1,2,3,4],[5,6,7,8]])
arr_y=np.array([[21,22,23,24],[25,26,27,28]])

In [124]:
arr_x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [125]:
arr_y

array([[21, 22, 23, 24],
       [25, 26, 27, 28]])

In [127]:
arr_z=np.concatenate((arr_x,arr_y),axis=1)

In [128]:
print(arr_z)
arr_z.shape

[[ 1  2  3  4 21 22 23 24]
 [ 5  6  7  8 25 26 27 28]]


(2, 8)

In [129]:
arr_z=np.concatenate((arr_x,arr_y),axis=0)

In [130]:
print(arr_z)
arr_z.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]


(4, 4)

In [131]:
print(arr_x)
print()
print(arr_y)
print()
print(arr_z)

[[1 2 3 4]
 [5 6 7 8]]

[[21 22 23 24]
 [25 26 27 28]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]


In [132]:
np.hsplit(arr_z,4)

[array([[ 1],
        [ 5],
        [21],
        [25]]), array([[ 2],
        [ 6],
        [22],
        [26]]), array([[ 3],
        [ 7],
        [23],
        [27]]), array([[ 4],
        [ 8],
        [24],
        [28]])]

In [133]:
np.vsplit(arr_z,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[21, 22, 23, 24]]),
 array([[25, 26, 27, 28]])]